Limit threads
purescript/psc-package pull request #127
Opened 2018-07-17 13:08 UTC by vladciobanu

This is more of a "is this what you had in mind", I'm totally open to feedback.

I added a `--threads N` option for all commands that (eventually) hit a `mapConcurrently` or a `forConcurrently_`. I did it by adding a `Maybe Int` parameter down the call stack (not sure if it's worth it refactoring all of the functions to some `ReaderT env IO`; probably not with this PR but I could take that on if it would get accepted).

A value of `Nothing` means use old behaviour, otherwise use the method suggested by @kRITZCREEK's link in #126.

I would also like to keep the changes to the import because I like them arranged nicely, but I'm totally fine reverting that chunk if you want me to.

This has been tested on Appveyor on our project and fixed our issues. We have only tested with `--threads 1` so far and that works (but is obviously a bit slow).

2018-07-17 13:25 UTC, justinwoo commented on app/Main.hs
> +          <> Opts.help "Limit the number of threads"
Needs better explanation

2018-07-17 13:26 UTC, justinwoo commented on app/Main.hs
> +import           Data.Either.Combinators      (rightToMaybe)
I really would rather not have all of these diff changes because it makes maintenance harder

2018-07-17 13:28 UTC, justinwoo commented
This sounds fine overall? Just I guess we should do a pre-release in any case if we merge this to see if anyone has problems with this.

2018-07-17 13:30 UTC, vladciobanu commented
No rush for me, we've included the binary from this branch in our repo until it's up on `chocolatey`.

2018-07-17 13:39 UTC, kritzcreek requested changes
I don't think we should be using the word thread, it's jobs not threads that we are limiting here (so the word thread might mislead someone).

2018-07-17 13:39 UTC, kRITZCREEK commented on psc-package.cabal
> +                   SafeSemaphore -any
No need to depend on this package, the bugs in base's semaphore have been fixed.

2018-07-17 20:03 UTC, vladciobanu commented on app/Main.hs
> +          <> Opts.help "Limit the number of threads"
How about renaming it to `jobs` and the text to _Limit the number of jobs that can run concurrently_?

2018-07-17 21:46 UTC, eviefp commented
Thanks for the reviews, I think I addressed the issues. Let me know if the current message is okay @justinwoo 

I haven't tested it yet, will do that tomorrow at work on our codebase and will update then.

2018-07-18 15:29 UTC, vladciobanu commented
Alright, after a bit of confusion I think everything is working correctly. Tested it on appveyor and it works just fine with up to 6 jobs. Didn't encounter any issues with this version.

2018-07-19 05:26 UTC, kritzcreek requested changes

2018-07-19 05:26 UTC, kritzcreek commented on app/Main.hs
> +          mapConcurrently (\x -> waitQSem sem *> dirFor x <* signalQSem sem) dependencies
You'll want to use `bracket_ (waitQSem sem) (signalQSem sem) (dirFor x)` to make sure you don't lose a capacity on exception in `dirFor`.

EDIT:

I got that one from http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Concurrent-QSem.html#t:QSem

2018-07-19 10:36 UTC, vladciobanu commented on app/Main.hs
> +          mapConcurrently (\x -> waitQSem sem *> dirFor x <* signalQSem sem) dependencies
Good catch, thank you!

2018-07-19 11:00 UTC, vladciobanu commented
Added `bracket_`, made sure there's no more formatting noise and tested it on our appveyor. Seems to work even with jobs = 10, but still fails with unlimited.

If you mind the Makefile I could remove that too.

2018-07-19 11:26 UTC, kritzcreek approved these changes

2018-07-19 16:20 UTC, merged

2018-07-19 16:21 UTC, justinwoo commented
Thanks! I made a pre-release here: https://github.com/purescript/psc-package/releases/tag/v0.4.1-pre